# Product Rules - Essential - Positive
# These are Spectral rules that get applied at the product scope, walking through what needs to be done when building a product, but then also linting the end result to ensure a compliant schema.

rules:

  #-------------------------
  # Policy - Product - Name
  #-------------------------

  product-v1-name:

    description: Product Name
    message: The product has a name.
    documentationUrl: https://bbgithub.dev.bloomberg.com/webapi/rules
    given: "$"
    severity: info
    recommended: true
    type: style
    then:
      field: name
      function: falsy

  product-v1-name-upper-case:

    description: Product Name Upper Case
    message: The product name is capitalized.
    documentationUrl: https://bbgithub.dev.bloomberg.com/webapi/rules
    given: "$.name"
    then:
      function: pattern
      functionOptions:
        notMatch: "^[A-Z][a-z]*(?: [A-Z][a-z]*)*$"
    type: style
    recommended: true
    severity: info

  product-v1-name-max-length:

    description: Product Name Max Length
    message: The product name is not too long.
    documentationUrl: https://bbgithub.dev.bloomberg.com/webapi/rules
    given: "$"
    severity: info
    recommended: true
    type: style
    then:
      field: name
      function: length
      functionOptions:
        max: 50

  #------------------
  # Policy - Product - Description
  #------------------

  product-v1-description:

    description: Product Description
    message: There is product description.
    given: "$"
    severity: info
    recommended: true
    type: style
    then:
      field: description
      function: falsy

  product-v1-description-max-length:

    description: Product Description Max Length
    message: The product description is not too long.
    given: "$"
    severity: info
    recommended: true
    type: style
    then:
      field: description
      function: length
      functionOptions:
        max: 50

  #------------------
  # Policy - Product - Owners
  #------------------

  product-v1-owners:

    description: Owners
    message: There is an owner object.
    severity: info
    given: "$"
    then:
    - field: owners
      function: falsy

  product-v1-owners-one:

    description: Owners One
    message: There is one owner.
    given: "$"
    severity: info
    then:
      field: owners
      function: length
      functionOptions:
        min: 1
    type: style

  product-v1-owners-pwho:

    description: Owners PWHO
    message: Owners have a PWHO.
    severity: info
    given: "$.owners.*"
    then:
    - field: pwho
      function: falsy

 #------------------
  # Policy - Product - Use Case
  #------------------

  product-v1-use-cases:

    description: Use Cases
    message: There is a use case object.
    severity: info
    given: "$"
    then:
    - field: use_cases
      function: falsy

  product-v1-use-cases-one:

    description: Use Cases One
    message: There is a use case.
    given: "$"
    severity: info
    then:
      field: use_cases
      function: length
      functionOptions:
        min: 1
    type: style

 #------------------
  # Policy - Product - Specs
  #------------------

  product-v1-specs:

    description: Specs
    message: There is a specs object.
    severity: info
    given: "$"
    then:
    - field: specs
      function: falsy

  product-v1-specs-one:

    description: Specs One
    message: There is a spec.
    given: "$"
    severity: info
    then:
      field: specs
      function: length
      functionOptions:
        min: 1
    type: style

 #------------------
  # Policy - Product - Routes
  #------------------

  product-v1-routes:

    description: Routes
    message: There is a routes object.
    severity: info
    given: "$"
    then:
    - field: routes
      function: falsy

  product-v1-routes-one:

    description: Routes One
    message: There is a route.
    given: "$"
    severity: info
    then:
      field: routes
      function: length
      functionOptions:
        min: 1
    type: style

 #------------------
  # Policy - Product - Versions
  #------------------

  product-v1-versions:

    description: Versions
    message: There is a version object.
    severity: info
    given: "$"
    then:
    - field: versions
      function: falsy

  product-v1-versions-one:

    description: Versions One
    message: There is a version.
    given: "$"
    severity: info
    then:
      field: versions
      function: length
      functionOptions:
        min: 1
    type: style

 #------------------
  # Policy - Product - Documents
  #------------------

  product-v1-documents:

    description: Documents
    message: There is a documents object.
    severity: info
    given: "$"
    then:
    - field: documents
      function: falsy

  product-v1-documents-one:

    description: Documents One
    message: There is one document.
    given: "$"
    severity: info
    then:
      field: documents
      function: length
      functionOptions:
        min: 1
    type: style

  product-v1-documents-name:

    description: Documents Name
    message: Each document should have a name.
    severity: info
    given: "$.documents.*"
    then:
    - field: name
      function: falsy

  product-v1-documents-description:

    description: Documents Description
    message: Each document should have a description.
    severity: info
    given: "$.documents.*"
    then:
    - field: description
      function: falsy

  product-v1-documents-type:

    description: Documents Type
    message: Each document should have a type.
    severity: info
    given: "$.documents.*"
    then:
    - field: type
      function: falsy

  product-v1-documents-type-specific:

    description: Documents Type
    message: There is getting started or functional document.
    severity: info
    given: "$.documents.*"
    then:

      - field: type
        function: pattern
        functionOptions:
          notMatch: /^(Getting Started|Functional)$/i

 #------------------
  # Policy - Product - Regions
  #------------------

  product-v1-regions:

    description: Regions
    message: There is a regions object.
    severity: info
    given: "$"
    then:
    - field: regions
      function: falsy

  product-v1-regions-one:

    description: Regions One
    message: There is one region.
    given: "$"
    severity: info
    then:
      field: regions
      function: length
      functionOptions:
        min: 1
    type: style

 #------------------
  # Policy - Product - Scores
  #------------------

  product-v1-scores:

    description: Scores
    message: There is a scores object.
    severity: info
    given: "$"
    then:
    - field: scores
      function: falsy

  product-v1-scores-one:

    description: Scores One
    message: There is one score.
    given: "$"
    severity: info
    then:
      field: scores
      function: length
      functionOptions:
        min: 1
    type: style

 #------------------
  # Policy - Product - Reviews
  #------------------

  product-v1-reviews:

    description: Reviews
    message: There is a reviews object.
    severity: info
    given: "$"
    then:
    - field: reviews
      function: falsy

  product-v1-reviews-one:

    description: Reviews One
    message: There is a review.
    given: "$"
    severity: info
    then:
      field: reviews
      function: length
      functionOptions:
        min: 1
    type: style

  #------------------
  # Policy - Product - Tags
  #------------------

  product-v1-tags:

    description: Tags
    message: There is a tags object.
    severity: info
    given: "$"
    then:
    - field: tags
      function: falsy

  product-v1-tags-one:

    description: Tags One
    message: There is a tag.
    given: "$"
    severity: info
    then:
      field: tags
      function: length
      functionOptions:
        min: 1
    type: style
